[package]
name = "dxf2elmt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = false  # Automatically strip symbols from the binary.
lto = false

[dependencies]
dxf = "0.5.0"
simple-xml-builder = "1.1.0"
bspline = "1.1.0"